### ISSUE TITLE
Searching for a hashtag is slow

### ISSUE THREAD

**Issue by eggpi** [WikipediaLibrary/hashtags#70]
As far as I can tell, searching for any hashtag seems to take multiple seconds and even times out sometimes. We should look into optimizing this.

As a simple first step, we could log the output of [explain](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#explain) on the [queryset used in searches](https://github.com/WikipediaLibrary/hashtags/blob/master/hashtagsv2/hashtags/helpers.py#L93) to see if we're doing something funny like a full-table scan. For my own future reference, [here's the documentation for interpreting that output](https://dev.mysql.com/doc/refman/8.0/en/explain-output.html).

It would also be good to experiment with a [profiler](https://docs.python.org/3/library/profile.html) to get a breakdown of the wall-clock time of a query. I think it's likely that the bottleneck is the database query (because the rest of the code is pretty standard use of Django), but we shouldn't take that for granted and this would allow us to identify other bad spots.

@Samwalton9 would you be able to try the above in the production environment please?

**Comment by Samwalton9** [comment]
I might not find time for this at the moment, but I'd be happy to get you a copy of the production database for local testing, if that would be helpful.

**Comment by eggpi** [comment]
Sure, let's try that. If I can reproduce it like that, it's even better.

**Comment by Samwalton9** [comment]
https://drive.google.com/file/d/1iyX0EEmeJhqS_6jImG1Q4gu1_xLnAbmU/view?usp=sharing

Let me know when you've downloaded the file so I can reclaim some Google Drive storage space :)

**Comment by eggpi** [comment]
Downloaded, thanks!

**Comment by eggpi** [comment]
I think there are two main sources of slowness here:

- Missing database indexes for some important queries.
- Accidental evaluation of Django QuerySets. We _attempt_ to use pagination for search results, but we end up running both a paginated query (SQL with `OFFSET` / `LIMIT` clauses) and its non-paginated, slow version.

I have a couple of fairly simple patches to address those issues and, in local experiments, they make a big difference: we essentially go from always timing out when searching for the "Trending tags", to serving the search within 3 seconds or so.

The one thing I'm not proposing we try yet is an optimization within Django's pagination (that's my f277fe8a9d84cbc84c764e5644caf1f6c9ab5dbb), as that one actually has behavior changes to the tool other than the speed.

I'll open a pull request with the more conservative patches, let's see how they behave in production.

**Comment by Samwalton9** [comment]
Per https://github.com/WikipediaLibrary/hashtags/pull/71#issuecomment-886620302 we've just made huge gains in tool speed!

**Comment by eggpi** [comment]
It looks like there's still some bad performance when querying for many hashtags at once ([example query](https://hashtags.wmflabs.org/graph/?query=WPWP%2C+WPWPRW%2C+WPWPRT%2C+WPWPUIL%2C+WPWPTH%2C+WPWPQS%2C+WPWPCA%2C+WPWPCM%2C+WPWPIN%2C+WPWPMK%2C+WPWPNG%2C+WPWPTR%2C+WPWPLV%2C+WPWPTZ%2C+WPWPZM%2C+WPWPPT%2C+WPWPBW%2C+WPWPML%2C+WPWPGN%2C+WPWPIT%2C+WPWPDZ%2C+WPWPHI%2C+WPWPSR%2C+WPWPWLF%2C+WPWPBE%2C+WPWPPH%2C+WPWPIG%2C+WLA%2C+WPWPCB%2C+WPWPTE%2C+WPWPMU%2C+WPWPSU%2C+WPWPDC%2C+WPWPUG%2C+WPWPAM%2C+WPWPWAM%2C+WPWPCH%2C+WPWPMIN%2C+WPWPUK%2C+WPWPARK%2C+WPWPBI%2C+WPWPTMZ%2C+WPWPGOA%2C+WPWPBN%2C+WPWPGC%2C+WPWPNL%2C+WPWPEO%2C+WPWPUAE%2C+WPWPWC%2C+WPWPIM%2C+WPWPUI%2C+WPWPVWW%2C+WPWPJV%2C+WPWPWD%2C+WPWPAR%2C+WPWPSUN%2C+WPWPIE%2CWPWPEG%2C+WPWPPK%2C+WWH%2C+WPWPHU%2C+WPWPW&project=&startdate=2021-07-01&enddate=2021-08-31&search_type=or&user=)).

I need to check whether this is some other unoptimized code path, but at this point we might need to consider patches that change the UI (e.g. break the pagination of results).

**Comment by eggpi** [comment]
Things are looking a little better now I think. I'm seeing [the test query](https://hashtags.wmflabs.org/graph/?query=WPWP%2C+WPWPRW%2C+WPWPRT%2C+WPWPUIL%2C+WPWPTH%2C+WPWPQS%2C+WPWPCA%2C+WPWPCM%2C+WPWPIN%2C+WPWPMK%2C+WPWPNG%2C+WPWPTR%2C+WPWPLV%2C+WPWPTZ%2C+WPWPZM%2C+WPWPPT%2C+WPWPBW%2C+WPWPML%2C+WPWPGN%2C+WPWPIT%2C+WPWPDZ%2C+WPWPHI%2C+WPWPSR%2C+WPWPWLF%2C+WPWPBE%2C+WPWPPH%2C+WPWPIG%2C+WLA%2C+WPWPCB%2C+WPWPTE%2C+WPWPMU%2C+WPWPSU%2C+WPWPDC%2C+WPWPUG%2C+WPWPAM%2C+WPWPWAM%2C+WPWPCH%2C+WPWPMIN%2C+WPWPUK%2C+WPWPARK%2C+WPWPBI%2C+WPWPTMZ%2C+WPWPGOA%2C+WPWPBN%2C+WPWPGC%2C+WPWPNL%2C+WPWPEO%2C+WPWPUAE%2C+WPWPWC%2C+WPWPIM%2C+WPWPUI%2C+WPWPVWW%2C+WPWPJV%2C+WPWPWD%2C+WPWPAR%2C+WPWPSUN%2C+WPWPIE%2CWPWPEG%2C+WPWPPK%2C+WWH%2C+WPWPHU%2C+WPWPW&project=&startdate=2021-07-01&enddate=2021-08-31&search_type=or&user=) load in around 20s, which is not great, but better than consisten 502s.
