### ISSUE TITLE
Delayed results

### ISSUE THREAD

**Issue by Anthere** [WikipediaLibrary/hashtags#76]
Since around last summer, when we use the hashtag tool, it does not display results on « recent » time slots. 
This seems to be getting worse. 
For example, I currently run a #shesaid campaign on Wikiquote. I got results till end of September, but not after the 30th. And we are end of November
Last summer, we were running the #WPWP campaign, closing Aug 30, and most results of the last results only showed up in the tool mid to end of September
Is there a practical reason for that ?

**Comment by eggpi** [comment]
Sorry for the delayed response, @Samwalton9 is investigating now.

**Comment by Samwalton9** [comment]
Apologies for the delay, this is all fixed, per my comment in https://phabricator.wikimedia.org/T296410#7569487. Data collection is slowly catching up.
